highlighter: pygments
markdown: redcarpet
pygments: true
exclude: [README.md]
relative_permalinks: false
category_dir: news/categories
category_title_prefix: "Category: "
name: Spec
description: All the news about Spec
feed_url: http://spec.st